spring.application.name=springAdoption

spring.threads.virtual.enabled=true

spring.data.redis.repositories.enabled=false
logging.level.org.springframework.data.repository.config=WARN

#DB PROPERTIES
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringAdoption
spring.datasource.username=postgres
spring.datasource.password=sodtgarfield

#SERVER
spring.sql.init.mode=never
server.port=7070

spring.session.store-type=none

spring.data.redis.host=localhost
spring.data.redis.port=6379

cache.ttl-hours=1
otp.redis.ttl-minutes=10

#SMTP server

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=5fb088ca9a7cf8
spring.mail.password=be98b713ecd2cc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.debug=false

onboarding.phone.max-entries=4