package com.bank.central.common.exception;

import lombok.Getter;

@Getter
public enum ErrorCode {

    CUSTOMER_ONBOARDING_FIRST_NAME_REQUIRED(1, "CUSTOMER_ONBOARDING_FIRST_NAME_REQUIRED"),
    CUSTOMER_ONBOARDING_LAST_NAME_REQUIRED(2, "CUSTOMER_ONBOARDING_LAST_NAME_REQUIRED"),
    CUSTOMER_ONBOARDING_EMAIL_REQUIRED(3, "CUSTOMER_ONBOARDING_EMAIL_REQUIRED"),
    CUSTOMER_ONBOARDING_INVALID_EMAIL(4, "CUSTOMER_ONBOARDING_INVALID_EMAIL"),
    CUSTOMER_ONBOARDING_INVALID_PHONE(5, "CUSTOMER_ONBOARDING_INVALID_PHONE"),
    CUSTOMER_ONBOARDING_EMAIL_EXISTS(6, "CUSTOMER_ONBOARDING_EMAIL_EXISTS"),
    CUSTOMER_ONBOARDING_PHONE_LIMIT_REACHED(7, "CUSTOMER_ONBOARDING_PHONE_LIMIT_REACHED"),

    CUSTOMER_NOT_FOUND(10, "CUSTOMER_NOT_FOUND"),
    ONBOARDING_NOT_FOUND(11, "ONBOARDING_NOT_FOUND"),
    ONBOARDING_INVALID_STATE(12, "ONBOARDING_INVALID_STATE"),
    CUSTOMER_INACTIVE(13, "CUSTOMER_INACTIVE"),

    OTP_NOT_FOUND(20, "OTP_NOT_FOUND"),
    OTP_REQUEST_MISMATCH(21, "OTP_REQUEST_MISMATCH"),
    OTP_INVALID(22, "OTP_INVALID"),
    OTP_LOCKED(24, "OTP_LOCKED"),

    ACCOUNT_NOT_FOUND(30, "ACCOUNT_NOT_FOUND"),
    ACCOUNT_INACTIVE(31, "ACCOUNT_INACTIVE"),

    INSUFFICIENT_FUNDS(50, "INSUFFICIENT_FUNDS"),
    ACCOUNT_OTP_NOT_VERIFIED(51, "ACCOUNT_OTP_NOT_VERIFIED"),
    INVALID_TRANSFER(52, "INVALID_TRANSFER"),
    SEND_MONEY_OTP_NOT_VERIFIED(53, "SEND_MONEY_OTP_NOT_VERIFIED"),

    AUTH_INVALID_CREDENTIALS(60, "AUTH_INVALID_CREDENTIALS"),
    AUTH_PASSWORD_ALREADY_SET(61, "AUTH_PASSWORD_ALREADY_SET"),
    AUTH_PASSWORD_NOT_ALLOWED(62, "AUTH_PASSWORD_NOT_ALLOWED"),
    AUTH_UNAUTHORIZED(63, "AUTH_UNAUTHORIZED"),

    INTERNAL_ERROR(999, "INTERNAL_ERROR");

    private final int id;
    private final String code;

    ErrorCode(int id, String code) {
        this.id = id;
        this.code = code;
    }
}
